packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  bcrypt: true
  bufferutil: true
  canvas: true
  core-js: true
  esbuild: true
  tesseract.js: true

onlyBuiltDependencies:
  - bcrypt
  - bufferutil
  - esbuild
  - core-js
  - canvas
