apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: arangodb-credentials
  namespace: okiru-pro
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: azure-kv-store
  target:
    name: arangodb-credentials
    creationPolicy: Owner
  data:
    - secretKey: ARANGO_ROOT_PASSWORD
      remoteRef:
        key: arango-root-password
    - secretKey: ARANGO_URL
      remoteRef:
        key: arango-url
    - secretKey: ARANGO_DB_NAME
      remoteRef:
        key: arango-db-name
