apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mongodb-credentials
  namespace: okiru-pro
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: azure-kv-store
  target:
    name: mongodb-credentials
    creationPolicy: Owner
  data:
    - secretKey: MONGO_INITDB_ROOT_USERNAME
      remoteRef:
        key: mongo-initdb-root-username
    - secretKey: MONGO_INITDB_ROOT_PASSWORD
      remoteRef:
        key: mongo-initdb-root-password
    - secretKey: MONGODB_URI
      remoteRef:
        key: mongodb-uri
    - secretKey: MONGODB_DB_NAME
      remoteRef:
        key: mongodb-db-name
