apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis-credentials
  namespace: okiru-pro
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: azure-kv-store
  target:
    name: redis-credentials
    creationPolicy: Owner
  data:
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: redis-password
    - secretKey: REDIS_URL
      remoteRef:
        key: redis-url
