apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: session-secrets
  namespace: okiru-pro
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: azure-kv-store
  target:
    name: session-secrets
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: jwt-secret
    - secretKey: SESSION_SECRET
      remoteRef:
        key: session-secret
    - secretKey: API_INTERNAL_KEY
      remoteRef:
        key: api-internal-key
