apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: okiru-pro-staging

resources:
  - ../../base

patchesStrategicMerge:
  - patches/ingress-patch.yaml
  - patches/resource-limits.yaml
  - patches/replica-count.yaml

images:
  - name: okiruproacrde4d539b.azurecr.io/okiru-pro/api
    newTag: staging
  - name: okiruproacrde4d539b.azurecr.io/okiru-pro/web
    newTag: staging
  - name: okiruproacrde4d539b.azurecr.io/okiru-pro/compute
    newTag: staging

commonLabels:
  environment: staging
  app.kubernetes.io/instance: okiru-pro-staging

configMapGenerator:
  - name: app-config
    behavior: merge
    literals:
      - NODE_ENV=staging
      - LOG_LEVEL=debug
      - CORS_ORIGIN="*"
