apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: okiru-pro-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
spec:
  rules:
    - host: staging.dilm.172.171.47.94.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 5001
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 5000
          - path: /compute
            pathType: Prefix
            backend:
              service:
                name: compute
                port:
                  number: 8000
