apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
    component: database
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
      name: mongodb
---
apiVersion: v1
kind: Service
metadata:
  name: arangodb
  labels:
    app: arangodb
    component: database
spec:
  type: ClusterIP
  selector:
    app: arangodb
  ports:
    - port: 8529
      targetPort: 8529
      name: arangodb
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
    component: cache
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
      name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
    component: backend
spec:
  type: ClusterIP
  selector:
    app: api
  ports:
    - port: 5000
      targetPort: 5000
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: web
    component: frontend
spec:
  type: ClusterIP
  selector:
    app: web
  ports:
    - port: 5001
      targetPort: 5001
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: compute
  labels:
    app: compute
    component: backend
spec:
  type: ClusterIP
  selector:
    app: compute
  ports:
    - port: 8000
      targetPort: 8000
      name: http
