import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { OKIRU_LOGO_BASE64 } from "./logo";
import { calculateOwnershipScore } from "./calculators/ownership";
import { calculateManagementScore } from "./calculators/management";
import { calculateSkillsScore } from "./calculators/skills";
import { calculateProcurementScore } from "./calculators/procurement";
import { calculateEsdScore, calculateSedScore } from "./calculators/esd-sed";

interface ExportOptions {
  analystName?: string;
  reportNotes?: string;
  includeDraft2026?: boolean;
  certificateNumber?: string;
  technicalSignatory?: string;
  docRevision?: string;
}

function formatCurrency(value: number): string {
  const abs = Math.abs(value);
  const formatted = `R ${abs.toLocaleString("en-ZA", { minimumFractionDigits: 0, maximumFractionDigits: 0 })}`;
  return value < 0 ? `-${formatted}` : formatted;
}

function fmt(value: number): string {
  return value.toFixed(2);
}

function pctStr(value: number): string {
  return `${value.toFixed(2)}%`;
}

const PURPLE: [number, number, number] = [109, 40, 217];
const PURPLE_LIGHT: [number, number, number] = [139, 92, 246];
const SLATE_900: [number, number, number] = [15, 23, 42];
const SLATE_700: [number, number, number] = [51, 65, 85];
const SLATE_500: [number, number, number] = [100, 116, 139];
const SLATE_400: [number, number, number] = [148, 163, 184];
const SLATE_200: [number, number, number] = [226, 232, 240];
const WHITE: [number, number, number] = [255, 255, 255];
const HEADER_BG: [number, number, number] = [245, 240, 255];

function addDocHeader(doc: jsPDF, docNo: string, revision: string) {
  const w = doc.internal.pageSize.width;
  doc.setFontSize(7);
  doc.setTextColor(...SLATE_400);
  doc.text(`Doc No: ${docNo}`, 15, 8);
  doc.text(`Revision No.: ${revision}`, w - 15, 8, { align: "right" });
}

function addDocFooter(doc: jsPDF, docNo: string, pageNum: number, totalPages: number) {
  const w = doc.internal.pageSize.width;
  const h = doc.internal.pageSize.height;
  doc.setDrawColor(...SLATE_200);
  doc.line(15, h - 15, w - 15, h - 15);
  doc.setFontSize(7);
  doc.setTextColor(...SLATE_400);
  doc.text(`${docNo} – Scorecard`, 15, h - 10);
  doc.text(`Page ${pageNum} of ${totalPages}`, w / 2, h - 10, { align: "center" });
  doc.text("Generated by Okiru.Pro", w - 15, h - 10, { align: "right" });
}

function sectionHeader(doc: jsPDF, num: string, title: string, y: number, margin: number): number {
  doc.setFontSize(12);
  doc.setTextColor(...PURPLE);
  doc.text(`${num}. ${title}:`, margin, y);
  y += 2;
  doc.setDrawColor(...PURPLE);
  doc.setLineWidth(0.5);
  doc.line(margin, y, margin + 40, y);
  return y + 5;
}

export const exportVerificationPdf = (state: any, options: ExportOptions = {}) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;
  const margin = 15;
  const today = new Date();
  const dateFormatted = today.toLocaleDateString("en-ZA", { day: "2-digit", month: "long", year: "numeric" });

  const currentLevel = state.scorecard.isDiscounted
    ? state.scorecard.discountedLevel
    : state.scorecard.achievedLevel;

  const certNumber =
    options.certificateNumber ||
    `OKR-${today.getFullYear()}-${String(Math.floor(Math.random() * 9999)).padStart(4, "0")}`;

  const docNo = `BO-${certNumber}`;
  const revision = options.docRevision || "01";
  const entityName = state.client.name;
  const tradeName = state.client.tradingName || state.client.tradeName || "";

  const defaultOwnership = { id: "", clientId: "", shareholders: [], companyValue: 0, outstandingDebt: 0, yearsHeld: 0, ownershipScorePoints: 0, ownershipScorePercent: 0, netValuePoints: 0, netValuePercent: 0 };
  const defaultManagement = { id: "", clientId: "", employees: [] };
  const defaultSkills = { id: "", clientId: "", leviableAmount: state.client?.leviableAmount || 0, trainingPrograms: [], yesCandidatesCount: 0, yesAbsorbedCount: 0 };
  const defaultProcurement = { id: "", clientId: "", tmps: 0, suppliers: [] };
  const defaultEsd = { id: "", clientId: "", contributions: [], graduationBonus: false, jobsCreatedBonus: false };
  const defaultSed = { id: "", clientId: "", contributions: [] };

  const cfg = state.calculatorConfig;
  let ownCalc: any, mgtCalc: any, skillCalc: any, procCalc: any, esdCalc: any, sedCalc: any;

  if (cfg) {
    ownCalc = calculateOwnershipScore(state.ownership || defaultOwnership, cfg);
    mgtCalc = calculateManagementScore(state.management || defaultManagement, cfg);
    skillCalc = calculateSkillsScore(state.skills || defaultSkills, cfg);
    procCalc = calculateProcurementScore(state.procurement || defaultProcurement, cfg);
    esdCalc = calculateEsdScore(state.esd || defaultEsd, state.client?.npat || 0, cfg);
    sedCalc = calculateSedScore(state.sed || defaultSed, state.client?.npat || 0, cfg);
  }

  // ─── PAGE 1: Cover Page ───
  doc.setFillColor(...PURPLE);
  doc.rect(0, 0, pageWidth, 12, "F");

  try {
    doc.addImage(OKIRU_LOGO_BASE64, "PNG", pageWidth / 2 - 25, 30, 50, 12);
  } catch {}

  doc.setDrawColor(...PURPLE);
  doc.setLineWidth(0.5);
  doc.line(pageWidth / 2 - 40, 48, pageWidth / 2 + 40, 48);

  doc.setFontSize(28);
  doc.setTextColor(...SLATE_900);
  doc.text("Final BEE", pageWidth / 2, 75, { align: "center" });
  doc.text("Verification Report", pageWidth / 2, 90, { align: "center" });

  doc.setDrawColor(...PURPLE_LIGHT);
  doc.setLineWidth(0.3);
  doc.line(pageWidth / 2 - 30, 96, pageWidth / 2 + 30, 96);

  doc.setFontSize(18);
  doc.setTextColor(...PURPLE);
  doc.text(entityName, pageWidth / 2, 115, { align: "center" });

  if (tradeName) {
    doc.setFontSize(13);
    doc.setTextColor(...SLATE_500);
    doc.text(`t/a ${tradeName}`, pageWidth / 2, 125, { align: "center" });
  }

  doc.setFontSize(14);
  doc.setTextColor(...SLATE_700);
  doc.text(dateFormatted, pageWidth / 2, 145, { align: "center" });

  doc.setFillColor(...PURPLE);
  doc.rect(0, doc.internal.pageSize.height - 12, pageWidth, 12, "F");

  // ─── PAGE 2: Entity Details + Scorecard Overview + B-BBEE Status ───
  doc.addPage();
  addDocHeader(doc, docNo, revision);
  let y = 16;

  y = sectionHeader(doc, "1", "Details of Measured Entity", y, margin);

  const entityRows: any[][] = [
    ["Company Name", entityName],
    ["Trade Name", tradeName || "—"],
    ["Address", state.client.physicalAddress || "—"],
    ["Registration Number", state.client.registrationNumber || "—"],
    ["Vat Number", state.client.vatNumber || "—"],
  ];

  autoTable(doc, {
    startY: y,
    body: entityRows,
    theme: "grid",
    styles: { fontSize: 9, cellPadding: 3, lineWidth: 0.2, lineColor: SLATE_200 },
    columnStyles: {
      0: { fontStyle: "bold", cellWidth: 55, textColor: SLATE_700 },
      1: { textColor: SLATE_900 },
    },
    alternateRowStyles: { fillColor: [250, 248, 255] },
    margin: { left: margin, right: margin },
  });
  y = (doc as any).lastAutoTable.finalY + 8;

  y = sectionHeader(doc, "2", "Scorecard Overview", y, margin);

  const scElements = [
    ["Equity Ownership", fmt(state.scorecard.ownership.score)],
    ["Management Control", fmt(state.scorecard.managementControl.score)],
    ["Employment Equity", "0.00"],
    ["Skills Development", fmt(state.scorecard.skillsDevelopment.score)],
    ["Preferential Procurement", fmt(state.scorecard.procurement.score)],
    ["Enterprise Development", fmt(state.scorecard.enterpriseDevelopment.score)],
    ["Socio Economic Development", fmt(state.scorecard.socioEconomicDevelopment.score)],
  ];

  const totalScore = state.scorecard.total.score;

  autoTable(doc, {
    startY: y,
    body: [...scElements, ["TOTAL SCORE", fmt(totalScore)]],
    theme: "grid",
    styles: { fontSize: 9, cellPadding: 3, lineWidth: 0.2, lineColor: SLATE_200 },
    columnStyles: {
      0: { fontStyle: "bold", cellWidth: 80, textColor: SLATE_700 },
      1: { halign: "right", textColor: SLATE_900, fontStyle: "bold" },
    },
    didParseCell: function (data) {
      if (data.section === "body" && data.row.index === scElements.length) {
        data.cell.styles.fillColor = HEADER_BG;
        data.cell.styles.textColor = PURPLE;
        data.cell.styles.fontStyle = "bold";
      }
    },
    margin: { left: margin, right: margin },
  });
  y = (doc as any).lastAutoTable.finalY + 8;

  y = sectionHeader(doc, "3", "B-BBEE Status", y, margin);

  const totalShareholders = state.ownership?.shareholders || [];
  const totalShares = totalShareholders.reduce((sum: number, sh: any) => sum + (sh.shares || 0), 0);
  const totalBlackOwnership =
    totalShares > 0
      ? totalShareholders.reduce((sum: number, sh: any) => sum + (sh.shares / totalShares) * sh.blackOwnership * 100, 0)
      : 0;
  const totalBlackFemale =
    totalShares > 0
      ? totalShareholders.reduce((sum: number, sh: any) => sum + (sh.shares / totalShares) * sh.blackWomenOwnership * 100, 0)
      : 0;

  const statusRows = [
    ["BEE Recognition Level", state.scorecard.recognitionLevel],
    ["BEE Status", currentLevel >= 9 ? "NON-COMPLIANT" : `LEVEL ${currentLevel}`],
    ["Black Ownership", pctStr(totalBlackOwnership)],
    ["Black Female Ownership", pctStr(totalBlackFemale)],
    ["Value-Adding Supplier", totalBlackOwnership >= 51 ? "YES" : "NO"],
    ["Applicable Scorecard", `${state.client.industry || "Generic"} - ${state.client.companySize || "Generic"}`],
    ["Certificate Number", certNumber],
    ["Verification Analyst", options.analystName || "—"],
    ["Technical Signatory", options.technicalSignatory || "—"],
  ];

  autoTable(doc, {
    startY: y,
    body: statusRows,
    theme: "grid",
    styles: { fontSize: 9, cellPadding: 3, lineWidth: 0.2, lineColor: SLATE_200 },
    columnStyles: {
      0: { fontStyle: "bold", cellWidth: 55, textColor: SLATE_700 },
      1: { textColor: SLATE_900 },
    },
    didParseCell: function (data) {
      if (data.section === "body" && data.row.index === 1) {
        const lvl = currentLevel;
        if (lvl <= 2) data.cell.styles.textColor = [22, 163, 74] as any;
        else if (lvl <= 4) data.cell.styles.textColor = PURPLE;
        else if (lvl >= 9) data.cell.styles.textColor = [239, 68, 68] as any;
      }
    },
    alternateRowStyles: { fillColor: [250, 248, 255] },
    margin: { left: margin, right: margin },
  });

  // ─── PAGE 3: Ownership Scorecard ───
  doc.addPage();
  addDocHeader(doc, docNo, revision);
  y = 16;
  y = sectionHeader(doc, "4", "Scorecard Summary", y, margin);

  doc.setFontSize(11);
  doc.setTextColor(...PURPLE);
  doc.text("Ownership", margin, y);
  y += 5;

  const shareholders = state.ownership?.shareholders || [];
  const votingBlackPct = totalShares > 0
    ? shareholders.reduce((s: number, sh: any) => s + (sh.shares / totalShares) * sh.blackOwnership * 100, 0)
    : 0;
  const economicBlackPct = votingBlackPct;
  const netValue = (state.ownership?.companyValue || 0) - (state.ownership?.outstandingDebt || 0);

  const ownershipTarget = state.scorecard.ownership.target || 25;
  const ownSubLines: any[][] = [];

  if (ownCalc) {
    ownCalc.subLines.forEach((sl: any) => {
      ownSubLines.push([sl.name, "", sl.weighting, sl.target, "", fmt(sl.score)]);
    });
  } else {
    ownSubLines.push(
      ["Voting Rights", "Exercisable Voting Rights in the Enterprise in the hands of black people", "", "25.01%", pctStr(votingBlackPct), ""],
      ["Economic Interest", "Economic Interest of black people in the Enterprise", "", "25.00%", pctStr(economicBlackPct), ""],
      ["Net Equity Value", "", "", "25.00%", formatCurrency(netValue), ""],
    );
  }

  autoTable(doc, {
    startY: y,
    head: [["Sub-Element", "Indicator", "Weighting\nPoints", "Compliance\nTarget", "Actual", "Score"]],
    body: ownSubLines,
    foot: [[{ content: "", colSpan: 2 }, "", "", "", fmt(state.scorecard.ownership.score)]],
    theme: "grid",
    headStyles: { fillColor: PURPLE, textColor: WHITE, fontSize: 8, fontStyle: "bold", halign: "center" },
    footStyles: { fillColor: HEADER_BG, textColor: PURPLE, fontStyle: "bold", fontSize: 9 },
    styles: { fontSize: 8, cellPadding: 3, lineWidth: 0.2, lineColor: SLATE_200 },
    columnStyles: {
      0: { cellWidth: 28, fontStyle: "bold", textColor: SLATE_700 },
      1: { cellWidth: 55 },
      2: { halign: "center", cellWidth: 18 },
      3: { halign: "center", cellWidth: 22 },
      4: { halign: "center", cellWidth: 25 },
      5: { halign: "center", cellWidth: 18, fontStyle: "bold" },
    },
    margin: { left: margin, right: margin },
  });
  y = (doc as any).lastAutoTable.finalY + 6;

  const ownershipDetailRows = [
    ["Total Issued Shares", totalShares.toLocaleString()],
    ["Number of Black Shares", shareholders.reduce((s: number, sh: any) => s + Math.round(sh.shares * sh.blackOwnership), 0).toLocaleString()],
    ["Number of Black Woman Shares", shareholders.reduce((s: number, sh: any) => s + Math.round(sh.shares * sh.blackWomenOwnership), 0).toLocaleString()],
    ["Value of Enterprise (NAV)", formatCurrency(state.ownership?.companyValue || 0)],
    ["Value of black shares", formatCurrency((state.ownership?.companyValue || 0) * (totalBlackOwnership / 100))],
    ["Debt in black shares", formatCurrency(state.ownership?.outstandingDebt || 0)],
    ["Time-based Graduation Factor", `${((state.ownership?.yearsHeld || 0) >= 10 ? 100 : (state.ownership?.yearsHeld || 0) * 10)}%`],
  ];

  autoTable(doc, {
    startY: y,
    body: ownershipDetailRows,
    theme: "plain",
    styles: { fontSize: 8, cellPadding: 2 },
    columnStyles: {
      0: { fontStyle: "bold", cellWidth: 60, textColor: SLATE_500 },
      1: { textColor: SLATE_900 },
    },
    margin: { left: margin, right: margin },
  });

  // ─── PAGE 4: Management Control + Employment Equity ───
  doc.addPage();
  addDocHeader(doc, docNo, revision);
  y = 16;

  doc.setFontSize(11);
  doc.setTextColor(...PURPLE);
  doc.text("Management Control", margin, y);
  y += 5;

  const mgtSubLines: any[][] = [];
  if (mgtCalc) {
    mgtCalc.subLines.forEach((sl: any) => {
      mgtSubLines.push([sl.name, "", sl.weighting, sl.target, "", fmt(sl.score)]);
    });
  } else {
    const employees = state.management?.employees || [];
    const topMgmt = employees.filter((e: any) => ["Board", "Executive Director", "Executive", "Other Executive Management"].includes(e.designation));
    const blackTopMgmt = topMgmt.filter((e: any) => ["African", "Coloured", "Indian"].includes(e.race));
    const blackWomenTopMgmt = blackTopMgmt.filter((e: any) => e.gender === "Female");
    const blackPct = topMgmt.length > 0 ? (blackTopMgmt.length / topMgmt.length) * 100 : 0;
    const bwPct = topMgmt.length > 0 ? (blackWomenTopMgmt.length / topMgmt.length) * 100 : 0;
    mgtSubLines.push(
      ["Top Management", "Black representation at Top Management", "25", "50.10%", pctStr(blackPct), fmt(state.scorecard.managementControl.score > 0 ? Math.min(25, state.scorecard.managementControl.score) : 0)],
      ["Bonus Points", "Black Women representation at Top Management", "2", "25.00%", pctStr(bwPct), ""],
    );
  }

  autoTable(doc, {
    startY: y,
    head: [["Sub-Element", "Indicator", "Weighting\nPoints", "Compliance\nTarget", "Actual", "Score"]],
    body: mgtSubLines,
    foot: [[{ content: "", colSpan: 2 }, "", "", "", fmt(state.scorecard.managementControl.score)]],
    theme: "grid",
    headStyles: { fillColor: [13, 148, 136], textColor: WHITE, fontSize: 8, fontStyle: "bold", halign: "center" },
    footStyles: { fillColor: [204, 251, 241], textColor: [13, 148, 136], fontStyle: "bold", fontSize: 9 },
    styles: { fontSize: 8, cellPadding: 3, lineWidth: 0.2, lineColor: SLATE_200 },
    columnStyles: {
      0: { cellWidth: 28, fontStyle: "bold", textColor: SLATE_700 },
      1: { cellWidth: 55 },
      2: { halign: "center", cellWidth: 18 },
      3: { halign: "center", cellWidth: 22 },
      4: { halign: "center", cellWidth: 25 },
      5: { halign: "center", cellWidth: 18, fontStyle: "bold" },
    },
    margin: { left: margin, right: margin },
  });
  y = (doc as any).lastAutoTable.finalY + 8;

  doc.setFontSize(11);
  doc.setTextColor(...PURPLE);
  doc.text("Employment Equity", margin, y);
  y += 5;

  const employees = state.management?.employees || [];
  const designations = ["Board", "Executive Director", "Other Executive Management", "Senior", "Middle", "Junior"];
  const races = ["African", "Coloured", "Indian", "White"];
  const raceAbbr: Record<string, string> = { African: "AM", Coloured: "CM", Indian: "IM" };

  const eqRows: any[][] = [];
  const eapProvince = state.client.eapProvince || "National";

  designations.forEach((d) => {
    const desg = employees.filter((e: any) => e.designation === d);
    const total = desg.length;
    if (total === 0) return;

    const african = desg.filter((e: any) => e.race === "African").length;
    const coloured = desg.filter((e: any) => e.race === "Coloured").length;
    const indian = desg.filter((e: any) => e.race === "Indian").length;
    const white = desg.filter((e: any) => e.race === "White").length;
    const black = african + coloured + indian;
    const blackF = desg.filter((e: any) => ["African", "Coloured", "Indian"].includes(e.race) && e.gender === "Female").length;

    eqRows.push([d, total, african, coloured, indian, white, black, pctStr((black / total) * 100), blackF, pctStr((blackF / total) * 100)]);
  });

  if (eqRows.length > 0) {
    const allBlack = employees.filter((e: any) => ["African", "Coloured", "Indian"].includes(e.race)).length;
    const allBF = employees.filter((e: any) => ["African", "Coloured", "Indian"].includes(e.race) && e.gender === "Female").length;
    eqRows.push(["TOTAL", employees.length, employees.filter((e: any) => e.race === "African").length, employees.filter((e: any) => e.race === "Coloured").length, employees.filter((e: any) => e.race === "Indian").length, employees.filter((e: any) => e.race === "White").length, allBlack, pctStr(employees.length > 0 ? (allBlack / employees.length) * 100 : 0), allBF, pctStr(employees.length > 0 ? (allBF / employees.length) * 100 : 0)]);

    autoTable(doc, {
      startY: y,
      head: [["Occupational Level", "Total", "African", "Coloured", "Indian", "White", "Black", "Black %", "Black\nWomen", "BWO %"]],
      body: eqRows,
      theme: "grid",
      headStyles: { fillColor: [79, 70, 229], textColor: WHITE, fontSize: 7, fontStyle: "bold", halign: "center" },
      styles: { fontSize: 7, cellPadding: 2, lineWidth: 0.2, lineColor: SLATE_200, halign: "center" },
      columnStyles: { 0: { halign: "left", fontStyle: "bold", textColor: SLATE_700 } },
      didParseCell: function (data) {
        if (data.section === "body" && data.row.index === eqRows.length - 1) {
          data.cell.styles.fillColor = [224, 231, 255];
          data.cell.styles.fontStyle = "bold";
        }
      },
      margin: { left: margin, right: margin },
    });
    y = (doc as any).lastAutoTable.finalY + 4;
  } else {
    doc.setFontSize(9);
    doc.setTextColor(...SLATE_500);
    doc.text("No employee data recorded.", margin, y + 3);
    y += 10;
  }

  doc.setFillColor(...HEADER_BG);
  doc.roundedRect(margin, y, pageWidth - margin * 2, 10, 2, 2, "F");
  doc.setFontSize(8);
  doc.setTextColor(...PURPLE);
  doc.text(`EAP Province: ${eapProvince}    |    Total Employees: ${employees.length}    |    Disabled: ${employees.filter((e: any) => e.isDisabled).length}`, margin + 4, y + 6);

  // ─── PAGE 5: Skills Development ───
  doc.addPage();
  addDocHeader(doc, docNo, revision);
  y = 16;

  doc.setFontSize(11);
  doc.setTextColor(...PURPLE);
  doc.text("Skills Development", margin, y);
  y += 5;

  const skillSubLines: any[][] = [];
  if (skillCalc) {
    skillCalc.subLines.forEach((sl: any) => {
      skillSubLines.push([sl.name, "", sl.weighting, sl.target, "", fmt(sl.score)]);
    });
  } else {
    skillSubLines.push(
      ["Skills Dev Expenditure", "Skills Development Expenditure on Learning Programmes for black employees as a % of Leviable Amount", "", "2.00%", "—", fmt(state.scorecard.skillsDevelopment.score)],
    );
  }

  autoTable(doc, {
    startY: y,
    head: [["Sub-Element", "Indicator", "Weighting\nPoints", "Compliance\nTarget", "Actual", "Score"]],
    body: skillSubLines,
    foot: [[{ content: "", colSpan: 2 }, "", "", "", fmt(state.scorecard.skillsDevelopment.score)]],
    theme: "grid",
    headStyles: { fillColor: [5, 150, 105], textColor: WHITE, fontSize: 8, fontStyle: "bold", halign: "center" },
    footStyles: { fillColor: [209, 250, 229], textColor: [5, 150, 105], fontStyle: "bold", fontSize: 9 },
    styles: { fontSize: 8, cellPadding: 3, lineWidth: 0.2, lineColor: SLATE_200 },
    columnStyles: {
      0: { cellWidth: 28, fontStyle: "bold", textColor: SLATE_700 },
      1: { cellWidth: 55 },
      2: { halign: "center", cellWidth: 18 },
      3: { halign: "center", cellWidth: 22 },
      4: { halign: "center", cellWidth: 25 },
      5: { halign: "center", cellWidth: 18, fontStyle: "bold" },
    },
    margin: { left: margin, right: margin },
  });
  y = (doc as any).lastAutoTable.finalY + 6;

  const programs = state.skills?.trainingPrograms || [];
  const leviable = state.skills?.leviableAmount || state.client?.leviableAmount || 0;
  const blackPrograms = programs.filter((p: any) => p.isBlack || ["African", "Coloured", "Indian"].includes(p.race));
  const blackSpend = blackPrograms.reduce((s: number, p: any) => s + (p.totalCost || p.cost || 0), 0);
  const totalSpend = programs.reduce((s: number, p: any) => s + (p.totalCost || p.cost || 0), 0);

  doc.setFontSize(9);
  doc.setTextColor(...SLATE_700);
  doc.text("Spend Summary", margin, y);
  y += 4;

  const spendSummary = [
    ["Total Training Spend", formatCurrency(totalSpend)],
    ["Black Recognised Spend", formatCurrency(blackSpend)],
    ["Leviable Amount", formatCurrency(leviable)],
    ["Target (6% of Leviable Amount)", formatCurrency(leviable * 0.06)],
    ["Spend as % of Leviable Amount", leviable > 0 ? pctStr((totalSpend / leviable) * 100) : "0.00%"],
  ];

  autoTable(doc, {
    startY: y,
    body: spendSummary,
    theme: "plain",
    styles: { fontSize: 8, cellPadding: 2 },
    columnStyles: {
      0: { fontStyle: "bold", cellWidth: 60, textColor: SLATE_500 },
      1: { textColor: SLATE_900 },
    },
    margin: { left: margin, right: margin },
  });
  y = (doc as any).lastAutoTable.finalY + 6;

  if (programs.length > 0) {
    doc.setFontSize(9);
    doc.setTextColor(...SLATE_700);
    doc.text("Training Programme Register", margin, y);
    y += 4;

    const catCounts: Record<string, { count: number; blackSpend: number; total: number }> = {};
    const cats = ["A", "B", "C", "D", "E", "F", "G", "learnership", "internship", "bursary", "short_course", "other"];
    cats.forEach((c) => (catCounts[c] = { count: 0, blackSpend: 0, total: 0 }));
    programs.forEach((p: any) => {
      const cat = p.categoryCode || p.category || "other";
      if (!catCounts[cat]) catCounts[cat] = { count: 0, blackSpend: 0, total: 0 };
      catCounts[cat].count += 1;
      const cost = p.totalCost || p.cost || 0;
      catCounts[cat].total += cost;
      const isBlack = p.isBlack || ["African", "Coloured", "Indian"].includes(p.race);
      if (isBlack) catCounts[cat].blackSpend += cost;
    });

    const catRows = Object.entries(catCounts)
      .filter(([, v]) => v.count > 0)
      .map(([k, v]) => [k.replace(/_/g, " ").toUpperCase(), v.count, formatCurrency(v.total), formatCurrency(v.blackSpend)]);

    if (catRows.length > 0) {
      autoTable(doc, {
        startY: y,
        head: [["Category", "Count", "Total Spend", "Black Spend"]],
        body: catRows,
        theme: "grid",
        headStyles: { fillColor: [5, 150, 105], textColor: WHITE, fontSize: 8, fontStyle: "bold" },
        styles: { fontSize: 8, cellPadding: 2, lineWidth: 0.2, lineColor: SLATE_200 },
        margin: { left: margin, right: margin },
      });
    }
  }

  // ─── PAGE 6: Preferential Procurement + Enterprise Development ───
  doc.addPage();
  addDocHeader(doc, docNo, revision);
  y = 16;

  doc.setFontSize(11);
  doc.setTextColor(...PURPLE);
  doc.text("Preferential Procurement", margin, y);
  y += 5;

  const procSubLines: any[][] = [];
  if (procCalc) {
    procCalc.subLines.forEach((sl: any) => {
      procSubLines.push([sl.name, "", sl.weighting, sl.target, "", fmt(sl.score)]);
    });
  } else {
    procSubLines.push(
      ["Procurement Spend", "B-BBEE Spend on all Suppliers based on the B-BBEE Procurement Recognition Levels as a Percentage of Total Procurement Spend", "", "40.00%", "—", fmt(state.scorecard.procurement.score)],
    );
  }

  autoTable(doc, {
    startY: y,
    head: [["Sub-Element", "Indicator", "Weighting\nPoints", "Compliance\nTarget", "Actual", "Score"]],
    body: procSubLines,
    foot: [[{ content: "", colSpan: 2 }, "", "", "", fmt(state.scorecard.procurement.score)]],
    theme: "grid",
    headStyles: { fillColor: [217, 119, 6], textColor: WHITE, fontSize: 8, fontStyle: "bold", halign: "center" },
    footStyles: { fillColor: [254, 243, 199], textColor: [217, 119, 6], fontStyle: "bold", fontSize: 9 },
    styles: { fontSize: 8, cellPadding: 3, lineWidth: 0.2, lineColor: SLATE_200 },
    columnStyles: {
      0: { cellWidth: 28, fontStyle: "bold", textColor: SLATE_700 },
      1: { cellWidth: 55 },
      2: { halign: "center", cellWidth: 18 },
      3: { halign: "center", cellWidth: 22 },
      4: { halign: "center", cellWidth: 25 },
      5: { halign: "center", cellWidth: 18, fontStyle: "bold" },
    },
    margin: { left: margin, right: margin },
  });
  y = (doc as any).lastAutoTable.finalY + 6;

  const suppliers = state.procurement?.suppliers || [];
  const RECOGNITION_TABLE: Record<number, number> = { 1: 1.35, 2: 1.25, 3: 1.1, 4: 1.0, 5: 0.8, 6: 0.6, 7: 0.5, 8: 0.1, 0: 0 };
  const tmps = state.procurement?.tmps || 0;
  let totSupSpend = 0;
  let totRecognised = 0;
  let tot51BO = 0;
  let tot30BWO = 0;
  let totEME = 0;
  let totQSE = 0;

  suppliers.forEach((s: any) => {
    const recFactor = RECOGNITION_TABLE[s.beeLevel] || 0;
    totSupSpend += s.spend;
    totRecognised += s.spend * recFactor;
    if (s.blackOwnership >= 0.51) tot51BO += s.spend;
    if ((s.blackWomenOwnership || 0) >= 0.3) tot30BWO += s.spend;
    if (s.enterpriseType === "eme") totEME += s.spend;
    if (s.enterpriseType === "qse") totQSE += s.spend;
  });

  const procDetailRows = [
    ["BEE Empowering Suppliers", formatCurrency(totRecognised), formatCurrency(tmps > 0 ? tmps * 0.4 : 0), tmps > 0 ? pctStr((totRecognised / (tmps * 0.4)) * 100) : "—"],
    ["QSE/EME Expenditure", formatCurrency(totEME + totQSE), "—", "—"],
    ["EME Expenditure", formatCurrency(totEME), "—", "—"],
    ["> 50% black owned", formatCurrency(tot51BO), "—", "—"],
    ["> 30% Black Women Owned", formatCurrency(tot30BWO), "—", "—"],
  ];

  autoTable(doc, {
    startY: y,
    head: [["B-BBEE Element", "Total Applied Spend", "Target", "% Achieved"]],
    body: procDetailRows,
    theme: "grid",
    headStyles: { fillColor: [217, 119, 6], textColor: WHITE, fontSize: 8, fontStyle: "bold" },
    styles: { fontSize: 8, cellPadding: 2, lineWidth: 0.2, lineColor: SLATE_200 },
    columnStyles: { 0: { fontStyle: "bold", textColor: SLATE_700 } },
    margin: { left: margin, right: margin },
  });
  y = (doc as any).lastAutoTable.finalY + 8;

  doc.setFontSize(11);
  doc.setTextColor(...PURPLE);
  doc.text("Enterprise Development", margin, y);
  y += 5;

  const esdContribs = state.esd?.contributions || [];
  const npat = state.client?.npat || 0;

  const esdSubLines: any[][] = [];
  if (esdCalc) {
    esdCalc.sdSubLines.forEach((sl: any) => {
      esdSubLines.push(["SD: " + sl.name, "", sl.weighting, sl.target, "", fmt(sl.score)]);
    });
    esdCalc.edSubLines.forEach((sl: any) => {
      esdSubLines.push(["ED: " + sl.name, "", sl.weighting, sl.target, "", fmt(sl.score)]);
    });
  } else {
    esdSubLines.push(
      ["ED Contributions", "Average annual value of all qualifying ED contributions as a percentage of NPAT", "", "2.00%", "—", fmt(state.scorecard.enterpriseDevelopment.score)],
    );
  }

  autoTable(doc, {
    startY: y,
    head: [["Sub-Element", "Indicator", "Weighting\nPoints", "Compliance\nTarget", "Actual", "Score"]],
    body: esdSubLines,
    foot: [[{ content: "", colSpan: 2 }, "", "", "", fmt(state.scorecard.enterpriseDevelopment.score)]],
    theme: "grid",
    headStyles: { fillColor: [190, 18, 60], textColor: WHITE, fontSize: 8, fontStyle: "bold", halign: "center" },
    footStyles: { fillColor: [255, 228, 230], textColor: [190, 18, 60], fontStyle: "bold", fontSize: 9 },
    styles: { fontSize: 8, cellPadding: 3, lineWidth: 0.2, lineColor: SLATE_200 },
    columnStyles: {
      0: { cellWidth: 28, fontStyle: "bold", textColor: SLATE_700 },
      1: { cellWidth: 55 },
      2: { halign: "center", cellWidth: 18 },
      3: { halign: "center", cellWidth: 22 },
      4: { halign: "center", cellWidth: 25 },
      5: { halign: "center", cellWidth: 18, fontStyle: "bold" },
    },
    margin: { left: margin, right: margin },
  });
  y = (doc as any).lastAutoTable.finalY + 4;

  const esdSummary = [
    ["Total Applied Contributions", formatCurrency(esdContribs.reduce((s: number, c: any) => s + c.amount, 0))],
    ["NPAT / Indicative NPAT", formatCurrency(npat)],
    ["Target (3% of NPAT)", formatCurrency(Math.abs(npat) * 0.03)],
  ];

  autoTable(doc, {
    startY: y,
    body: esdSummary,
    theme: "plain",
    styles: { fontSize: 8, cellPadding: 2 },
    columnStyles: {
      0: { fontStyle: "bold", cellWidth: 55, textColor: SLATE_500 },
      1: { textColor: SLATE_900 },
    },
    margin: { left: margin, right: margin },
  });

  // ─── PAGE 7: SED + YES + Total ───
  doc.addPage();
  addDocHeader(doc, docNo, revision);
  y = 16;

  doc.setFontSize(11);
  doc.setTextColor(...PURPLE);
  doc.text("Socio-Economic Development", margin, y);
  y += 5;

  const sedContribs = state.sed?.contributions || [];
  const sedTotal = sedContribs.reduce((s: number, c: any) => s + c.amount, 0);
  const sedTarget = Math.abs(npat) * 0.01;

  const sedSubLines: any[][] = [];
  if (sedCalc) {
    sedSubLines.push(["SED Contributions", "Average annual value of all qualifying SED Contributions as a percentage of NPAT", sedCalc.total > 0 ? "5" : "", "1.00%", sedTarget > 0 ? pctStr((sedTotal / sedTarget) * 100) : "—", fmt(sedCalc.total)]);
  } else {
    sedSubLines.push(
      ["SED Contributions", "Average annual value of all qualifying SED Contributions as a percentage of NPAT", "", "1.00%", sedTarget > 0 ? pctStr((sedTotal / sedTarget) * 100) : "—", fmt(state.scorecard.socioEconomicDevelopment.score)],
    );
  }

  autoTable(doc, {
    startY: y,
    head: [["Sub-Element", "Indicator", "Weighting\nPoints", "Compliance\nTarget", "Actual", "Score"]],
    body: sedSubLines,
    foot: [[{ content: "", colSpan: 2 }, "", "", "", fmt(state.scorecard.socioEconomicDevelopment.score)]],
    theme: "grid",
    headStyles: { fillColor: [37, 99, 235], textColor: WHITE, fontSize: 8, fontStyle: "bold", halign: "center" },
    footStyles: { fillColor: [219, 234, 254], textColor: [37, 99, 235], fontStyle: "bold", fontSize: 9 },
    styles: { fontSize: 8, cellPadding: 3, lineWidth: 0.2, lineColor: SLATE_200 },
    columnStyles: {
      0: { cellWidth: 28, fontStyle: "bold", textColor: SLATE_700 },
      1: { cellWidth: 55 },
      2: { halign: "center", cellWidth: 18 },
      3: { halign: "center", cellWidth: 22 },
      4: { halign: "center", cellWidth: 25 },
      5: { halign: "center", cellWidth: 18, fontStyle: "bold" },
    },
    margin: { left: margin, right: margin },
  });
  y = (doc as any).lastAutoTable.finalY + 4;

  const sedSummaryRows = [
    ["Applied Contribution", formatCurrency(sedTotal)],
    ["NPAT / Indicative NPAT", formatCurrency(npat)],
    ["Target (1% of NPAT)", formatCurrency(sedTarget)],
    ["Shortfall", sedTotal >= sedTarget ? formatCurrency(0) : `-${formatCurrency(sedTarget - sedTotal)}`],
  ];

  autoTable(doc, {
    startY: y,
    body: sedSummaryRows,
    theme: "plain",
    styles: { fontSize: 8, cellPadding: 2 },
    columnStyles: {
      0: { fontStyle: "bold", cellWidth: 55, textColor: SLATE_500 },
      1: { textColor: SLATE_900 },
    },
    margin: { left: margin, right: margin },
  });
  y = (doc as any).lastAutoTable.finalY + 8;

  doc.setFontSize(11);
  doc.setTextColor(...PURPLE);
  doc.text("Youth Employment Service Initiative (Y.E.S)", margin, y);
  y += 5;

  const yesScore = state.scorecard.yesInitiative?.score || 0;

  autoTable(doc, {
    startY: y,
    head: [["Sub-Element", "Indicator", "Weighting\nPoints", "Compliance\nTarget", "Actual", "Score"]],
    body: [
      ["Y.E.S Bonus Points", "Achieved Y.E.S Employment Target", "", "100.00%", "—", fmt(yesScore)],
    ],
    foot: [[{ content: "", colSpan: 2 }, "", "", "", fmt(yesScore)]],
    theme: "grid",
    headStyles: { fillColor: PURPLE_LIGHT, textColor: WHITE, fontSize: 8, fontStyle: "bold", halign: "center" },
    footStyles: { fillColor: HEADER_BG, textColor: PURPLE, fontStyle: "bold", fontSize: 9 },
    styles: { fontSize: 8, cellPadding: 3, lineWidth: 0.2, lineColor: SLATE_200 },
    columnStyles: {
      0: { cellWidth: 28, fontStyle: "bold", textColor: SLATE_700 },
      1: { cellWidth: 55 },
      2: { halign: "center", cellWidth: 18 },
      3: { halign: "center", cellWidth: 22 },
      4: { halign: "center", cellWidth: 25 },
      5: { halign: "center", cellWidth: 18, fontStyle: "bold" },
    },
    margin: { left: margin, right: margin },
  });
  y = (doc as any).lastAutoTable.finalY + 12;

  doc.setFillColor(...PURPLE);
  doc.roundedRect(margin, y, pageWidth - margin * 2, 22, 3, 3, "F");

  doc.setFontSize(12);
  doc.setTextColor(...WHITE);
  doc.text("TOTAL B-BBEE SCORE", margin + 8, y + 9);
  doc.setFontSize(16);
  doc.text(`${fmt(totalScore)} Points`, pageWidth - margin - 8, y + 9, { align: "right" });

  doc.setFontSize(12);
  doc.text("BROAD BASED CONTRIBUTION LEVEL", margin + 8, y + 18);
  doc.setFontSize(16);
  doc.text(currentLevel >= 9 ? "NON-COMPLIANT" : `LEVEL ${currentLevel}`, pageWidth - margin - 8, y + 18, { align: "right" });
  y += 30;

  if (options.reportNotes) {
    doc.setFontSize(9);
    doc.setTextColor(...SLATE_700);
    doc.text("Analyst Notes:", margin, y);
    y += 5;
    const noteLines = doc.splitTextToSize(options.reportNotes, pageWidth - margin * 2);
    doc.setFontSize(8);
    doc.text(noteLines, margin, y);
    y += noteLines.length * 4 + 6;
  }

  doc.setFontSize(7);
  doc.setTextColor(...SLATE_400);
  doc.text("This report is generated by Okiru.Pro and does not constitute a formal verification certificate.", margin, y);
  y += 4;
  doc.text("For formal verification, engage a SANAS-accredited B-BBEE verification agency.", margin, y);

  const totalPages = doc.internal.pages.length - 1;
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    addDocFooter(doc, docNo, i, totalPages);
  }

  const safeEntityName = entityName.replace(/[^a-zA-Z0-9]/g, "_");
  const dateStr = today.toISOString().split("T")[0];
  const fileName = `BEE_Verification_Report_${safeEntityName}_${dateStr}.pdf`;
  doc.save(fileName);
  return fileName;
};
