/**
 * Read a site × month table as monthly figures — deterministically.
 *
 * WHY THIS EXISTS
 *
 * The way companies actually keep environmental data is a dashboard: one sheet
 * per theme, a block per measure ("FUEL LITRES", "KM", "GENERATOR FUEL"), a row
 * per depot, a column per month. The ESG workbook's own grids have exactly that
 * shape — Scope 1A diesel, Scope 2 electricity, water — site by month.
 *
 * The parser read those sheets as if they were one flat document: the model
 * was asked for ONE `fuel_litres`, ONE `site_name`, ONE billing period per
 * sheet. A sheet holding 45 figures cannot answer that, so it gave one or none,
 * and the blocks below the first were flattened into stray rows under the
 * first block's header. A dashboard holding a year of depot data placed nothing.
 *
 * THE SPLIT OF LABOUR — the same one the register readers use:
 *   - CODE finds the structure: a run of consecutive month labels (across a row
 *     or down a column), the data rows or columns beside it, the title lines
 *     above it, the unit each line states, and which lines are totals.
 *   - The MODEL answers one closed question per table — which measure each line
 *     is, from a fixed list, in which unit, and which year the first month falls
 *     in — cached on the table's shape, so a template is asked about once.
 *   - CODE reads every number. Never a total row: a total is the place a
 *     spreadsheet goes wrong (a July total typed over as `3`, a November SUM
 *     that skips a depot), and the depot rows are the evidence.
 *
 * Each figure becomes one fact — measure, site as written, month, value, unit —
 * emitted as rows of `esg_monthly_rows`. Which grid, which depot row and which
 * month column it lands in is the workbook's decision, made on the web against
 * the company's own sites and reporting year. This file only says what the
 * document states.
 */
import { createLogger } from '../logger.js';
import type { DocumentExtraction, ExtractionModel } from './aiExtraction.js';
import { decisionFingerprint, rememberDecision } from './semanticDecisionCache.js';

const logger = createLogger('EsgMonthlyTables');

/** The monthly measures the ESG workbook keeps, and the unit each is stored in. */
export const ESG_MONTHLY_MEASURES = {
  'fleet.diesel_litres': { unit: 'L', what: 'diesel used by the delivery / road-freight fleet (trucks), litres' },
  'fleet.business_car_petrol_litres': { unit: 'L', what: 'fuel used by company or business cars (not freight trucks), litres' },
  'fleet.distance_km': { unit: 'km', what: 'distance driven by the fleet, kilometres' },
  'fleet.external_diesel_issued_litres': {
    unit: 'L',
    what: 'diesel issued from the company\'s own tanks to vehicles OUTSIDE its fleet ("external vehicles", contractors, third parties), litres',
  },
  'energy.generator_diesel_litres': { unit: 'L', what: 'diesel burned in standby generators, litres' },
  'energy.lpg_kg': { unit: 'kg', what: 'LPG / forklift gas, kilograms' },
  'energy.electricity_kwh': { unit: 'kWh', what: 'grid electricity consumed, kWh' },
  'energy.solar_kwh_generated': { unit: 'kWh', what: 'electricity generated by on-site solar, kWh' },
  'water.kl': { unit: 'kL', what: 'water consumed, kilolitres' },
} as const;

export type EsgMonthlyMeasure = keyof typeof ESG_MONTHLY_MEASURES;

/** Units the model may name, and what one of them is in the measure's stored unit. */
const UNIT_FACTORS: Record<string, Record<string, number>> = {
  L: { L: 1, kL: 1000 },
  kL: { kL: 1, L: 0.001, m3: 1, ML: 1000 },
  kWh: { kWh: 1, MWh: 1000 },
  kg: { kg: 1, t: 1000 },
  km: { km: 1 },
};

export interface EsgMonthlyFact {
  measure: EsgMonthlyMeasure;
  /** The site exactly as the document names it; null for a company-wide line. */
  site: string | null;
  /** Last day of the month, ISO. */
  period_end: string;
  value: number;
  unit: string;
}

/* ------------------------------------------------------------------ *
 * Month labels
 * ------------------------------------------------------------------ */

const MONTH_NAMES = ['jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct', 'nov', 'dec'];
const FULL_MONTH_NAMES = [
  'january', 'february', 'march', 'april', 'may', 'june',
  'july', 'august', 'september', 'october', 'november', 'december',
];

/** "JUL", "July", "Jul-25", "2025-07", or an Excel date serial for a month → month (+ year). */
export function readMonthLabel(cell: unknown, allowSerial: boolean): { month: number; year?: number } | null {
  if (typeof cell === 'number') {
    // Excel serials between 2000 and 2100; a serial is only trusted down a
    // column of consecutive months, which the caller checks.
    if (!allowSerial || !Number.isInteger(cell) || cell < 36526 || cell > 73051) return null;
    const date = new Date(Math.round((cell - 25569) * 86400 * 1000));
    return { month: date.getUTCMonth() + 1, year: date.getUTCFullYear() };
  }
  if (typeof cell !== 'string') return null;
  const text = cell.trim().toLowerCase().replace(/\.$/, '');
  const named = /^([a-z]{3,9})(?:[\s\-/']+(\d{2}|\d{4}))?$/.exec(text);
  if (named) {
    const index = MONTH_NAMES.indexOf(named[1].slice(0, 3));
    // "march" and "mar" yes; "marketing" no: the word must BE a month name.
    if (index < 0 || !(named[1].length === 3 || FULL_MONTH_NAMES[index].startsWith(named[1]) || named[1] === 'sept')) return null;
    const year = named[2] ? (named[2].length === 2 ? 2000 + Number(named[2]) : Number(named[2])) : undefined;
    return { month: index + 1, year };
  }
  const iso = /^(\d{4})[-/](\d{1,2})$/.exec(text);
  if (iso && Number(iso[2]) >= 1 && Number(iso[2]) <= 12) return { month: Number(iso[2]), year: Number(iso[1]) };
  return null;
}

const nextMonth = (m: number) => (m % 12) + 1;

interface MonthRun {
  /** Index of each month cell along the line, in order. */
  at: number[];
  months: number[];
  years: Array<number | undefined>;
}

/**
 * The longest run of CONSECUTIVE months along a line of cells, gaps allowed
 * (a month column followed by its "AMOUNT" column). Three or more is a header;
 * consecutiveness is what tells it from a sentence that mentions March.
 */
function monthRun(cells: unknown[], allowSerial: boolean): MonthRun | null {
  let best: MonthRun | null = null;
  let current: MonthRun | null = null;
  for (let i = 0; i < cells.length; i += 1) {
    const label = readMonthLabel(cells[i], allowSerial);
    if (!label) continue;
    if (current && label.month === nextMonth(current.months[current.months.length - 1])) {
      current.at.push(i);
      current.months.push(label.month);
      current.years.push(label.year);
    } else {
      current = { at: [i], months: [label.month], years: [label.year] };
    }
    if (!best || current.at.length > best.at.length) {
      best = { at: [...current.at], months: [...current.months], years: [...current.years] };
    }
  }
  return best && best.at.length >= 3 ? best : null;
}

/* ------------------------------------------------------------------ *
 * Tables
 * ------------------------------------------------------------------ */

const isBlank = (c: unknown) => c === null || c === undefined || String(c).trim() === '';
const asNumber = (c: unknown): number | null => {
  if (typeof c === 'number' && Number.isFinite(c)) return c;
  if (typeof c === 'string' && /^-?[\d\s,]*\.?\d+$/.test(c.trim())) {
    const n = Number(c.replace(/[\s,]/g, ''));
    return Number.isFinite(n) ? n : null;
  }
  return null;
};
const asText = (c: unknown) => (typeof c === 'string' ? c.replace(/\s+/g, ' ').trim() : '');

/** One line of figures beside a month run: a site (or a measure) and its numbers. */
export interface MonthLine {
  label: string;
  /** A second label beside the first — a unit ("LT", "KWH") or a landlord's name. */
  qualifier: string;
  /** Per month in the run: the figure, or null where the cell is empty. */
  values: Array<number | null>;
  isTotal: boolean;
}

export interface MonthTable {
  orientation: 'months-across' | 'months-down';
  /** Text lines above the table: its title. */
  title: string[];
  /** The cell where the line labels' header sits (often the company or site name). */
  corner: string;
  /** Unit labels stated under the months ("LPG - kg"), when the table has them. */
  monthUnits: string[];
  months: number[];
  years: Array<number | undefined>;
  lines: MonthLine[];
  /**
   * The second half of the table above it: no title of its own (the row above
   * is that table's total) and the same lines. A year split Jul–Dec / Jan–Jun is
   * one table laid out twice, and is read as one.
   */
  continues?: boolean;
}

/** Same lines in the same order — the mark of a table continued below itself. */
function sameLines(a: MonthTable, b: Pick<MonthTable, 'lines'>): boolean {
  const labels = (t: Pick<MonthTable, 'lines'>) => t.lines.filter((l) => !l.isTotal).map(lineKey).join('\n');
  return labels(a) !== '' && labels(a) === labels(b);
}

const TOTAL_LABEL = /^(grand\s+)?(sub-?)?totals?\b|^total\s/i;

function titleAbove(matrix: unknown[][], row: number): string[] {
  const title: string[] = [];
  for (let r = row - 1; r >= 0 && title.length < 3; r -= 1) {
    const cells = (matrix[r] ?? []).filter((c) => !isBlank(c));
    if (cells.length === 0) {
      if (title.length > 0) break;
      continue;
    }
    // A row of figures is the previous table, not this one's title.
    if (cells.some((c) => asNumber(c) !== null)) break;
    title.unshift(cells.map(asText).filter(Boolean).join(' · '));
  }
  return title;
}

/** Tables whose month labels run across a row. */
function tablesAcross(matrix: unknown[][]): MonthTable[] {
  const tables: MonthTable[] = [];
  for (let r = 0; r < matrix.length; r += 1) {
    const run = monthRun(matrix[r] ?? [], false);
    if (!run) continue;
    const firstCol = run.at[0];

    // A row of unit labels under the months ("LPG - kg | AMOUNT") belongs to the header.
    let dataStart = r + 1;
    let monthUnits: string[] = [];
    const under = matrix[r + 1] ?? [];
    if (run.at.every((c) => asNumber(under[c]) === null) && run.at.filter((c) => asText(under[c])).length >= run.at.length / 2) {
      monthUnits = run.at.map((c) => asText(under[c]));
      dataStart = r + 2;
    }

    const body: unknown[][] = [];
    let last = dataStart - 1;
    for (let d = dataStart; d < matrix.length; d += 1) {
      const row = matrix[d] ?? [];
      if (row.every(isBlank)) break;
      if (monthRun(row, false)) break;
      last = d;
      const values = run.at.map((c) => asNumber(row[c]));
      if (values.every((v) => v === null)) {
        // A label with no figures yet ("ALDER WAREHOUSE") is a line, not the end.
        if (row.slice(0, firstCol).some((c) => asText(c))) continue;
        break;
      }
      body.push(row);
    }
    if (body.length === 0) continue;

    // Labels are read by POSITION: the label column is the leftmost one left of
    // the months that names at least half the rows. A total row leaves it blank
    // and may still state its unit beside it ("" | "LT" | 3 | …) — read by
    // "first non-empty cell", that unit became a site called "LT".
    const textCount = (c: number) => body.filter((row) => asText(row[c])).length;
    const labelColumns = Array.from({ length: firstCol }, (_, c) => c).filter((c) => textCount(c) > 0);
    const labelCol = labelColumns.find((c) => textCount(c) * 2 >= body.length) ?? labelColumns[0] ?? -1;
    const qualifierCol = labelColumns.find((c) => c > labelCol) ?? -1;
    const lines: MonthLine[] = body.map((row) => {
      const label = labelCol >= 0 ? asText(row[labelCol]) : '';
      return {
        label,
        qualifier: qualifierCol >= 0 ? asText(row[qualifierCol]) : '',
        values: run.at.map((c) => asNumber(row[c])),
        isTotal: !label || TOTAL_LABEL.test(label),
      };
    });
    const title = titleAbove(matrix, r);
    const previous = tables[tables.length - 1];
    tables.push({
      orientation: 'months-across',
      title: title.length === 0 && previous && sameLines(previous, { lines }) ? previous.title : title,
      corner: firstCol > 0 ? asText((matrix[r] ?? [])[0]) : '',
      monthUnits,
      months: run.months,
      years: run.years,
      lines,
      continues: title.length === 0 && previous !== undefined && sameLines(previous, { lines }),
    });
    r = last;
  }
  return tables;
}

/** Tables whose months run DOWN a column (a summary sheet: a row per month, a column per measure). */
function tablesDown(matrix: unknown[][]): MonthTable[] {
  const width = matrix.reduce((w, row) => Math.max(w, row.length), 0); // not Math.max(...rows): spreading every row as an argument overflows the stack past ~120k rows
  for (let c = 0; c < width; c += 1) {
    const run = monthRun(matrix.map((row) => row[c]), true);
    if (!run) continue;
    const top = run.at[0];
    const header = top - 1;
    const group = top - 2;
    const lines: MonthLine[] = [];
    let carried = '';
    for (let k = c + 1; k < width; k += 1) {
      // A group header ("ROAD FREIGHT") spans several columns: carry it right.
      const groupLabel = group >= 0 ? asText((matrix[group] ?? [])[k]) : '';
      if (groupLabel) carried = groupLabel;
      const values = run.at.map((r) => asNumber((matrix[r] ?? [])[k]));
      if (values.filter((v) => v !== null).length < Math.ceil(run.at.length / 2)) continue;
      const own = header >= 0 ? asText((matrix[header] ?? [])[k]) : '';
      lines.push({ label: [carried, own].filter(Boolean).join(' › '), qualifier: '', values, isTotal: false });
    }
    if (lines.length === 0) continue;
    // One month column per sheet is the summary layout; a second would be a copy.
    return [{
      orientation: 'months-down',
      title: titleAbove(matrix, Math.max(0, group)),
      corner: header >= 0 ? asText((matrix[header] ?? [])[c]) : '',
      monthUnits: [],
      months: run.months,
      years: run.years,
      lines,
    }];
  }
  return [];
}

export function findMonthTables(matrix: unknown[][]): MonthTable[] {
  const across = tablesAcross(matrix);
  return across.length > 0 ? across : tablesDown(matrix);
}

/* ------------------------------------------------------------------ *
 * The one model question per table
 * ------------------------------------------------------------------ */

interface LineReading {
  measure: EsgMonthlyMeasure | 'none';
  unit: string;
}

export interface TableReading {
  /**
   * Whether each line is a SITE (rows are depots), a MEASURE of one site, or
   * something else — a vehicle, a person, an asset — which this reader does not
   * read (a vehicle register with monthly columns belongs to the register reader).
   */
  linesAre: 'sites' | 'measures' | 'other';
  /** The site a measures-table belongs to, when it names one. */
  site: string | null;
  /** The calendar year of the FIRST month, when the labels do not state it. */
  firstMonthYear: number | null;
  /** Keyed by lineKey. */
  lines: Record<string, LineReading>;
}

const SYSTEM = [
  "You read the structure of a table in a company's environmental spreadsheet for an ESG report.",
  'Its columns (or rows) are months. Each other line is a SITE (a depot, branch or warehouse), a',
  'MEASURE of one site, or something else entirely — a vehicle, a person, an asset — in which case',
  'answer lines_are "other" and nothing more. Say what each line measures, choosing ONLY from the list',
  'given, or "none" for money, tonnage, cases, counts, percentages and anything else not on the list.',
  'Give the unit the table states for that line. Work out the calendar year of the FIRST month from the',
  'sheet, title and file name (a "2025/2026" report that runs July to June starts in July 2025).',
  'Reply with JSON only.',
].join(' ');

/** A year range the file or title states ("2025-2026", "2025/26"), as [start, end]. */
export function statedYearRange(...texts: string[]): [number, number] | null {
  for (const text of texts) {
    const m = /\b(20\d{2})\s*[-/–]\s*(20\d{2}|\d{2})\b/.exec(text ?? '');
    if (!m) continue;
    const start = Number(m[1]);
    const end = m[2].length === 2 ? 2000 + Number(m[2]) : Number(m[2]);
    if (end === start + 1) return [start, end];
  }
  return null;
}

/** How a line is named in the question and the answer. */
export function lineKey(line: Pick<MonthLine, 'label' | 'qualifier'>): string {
  return `${line.label}|${line.qualifier}`;
}

function measureCatalogue(): string {
  return Object.entries(ESG_MONTHLY_MEASURES)
    .map(([key, spec]) => `  ${key}: ${spec.what} (stored in ${spec.unit})`)
    .join('\n');
}

async function readTable(
  model: ExtractionModel,
  table: MonthTable,
  context: { filename: string; sheetName?: string },
): Promise<TableReading | null> {
  const lines = table.lines.filter((line) => !line.isTotal);
  if (lines.length === 0) return null;
  const sample = lines.slice(0, 16).map((line) => ({
    key: lineKey(line),
    label: line.label,
    qualifier: line.qualifier || undefined,
    first_values: line.values.filter((v) => v !== null).slice(0, 3),
  }));
  const user = [
    `FILE: ${context.filename}`,
    `SHEET: ${context.sheetName ?? ''}`,
    `TITLE: ${table.title.join(' / ') || '(none)'}`,
    `CORNER CELL: ${table.corner || '(none)'}`,
    `MONTHS: ${table.months.map((m) => MONTH_NAMES[m - 1]).join(', ')}${table.years[0] ? ` (first stated as ${table.years[0]})` : ''}`,
    table.monthUnits.length ? `UNITS UNDER THE MONTHS: ${Array.from(new Set(table.monthUnits)).join(', ')}` : '',
    `LINES: ${JSON.stringify(sample)}`,
    'MEASURES:',
    measureCatalogue(),
    'UNITS you may name: L, kL, m3, ML, kWh, MWh, kg, t, km, other.',
    'Reply: {"lines_are":"sites"|"measures"|"other","site":string|null,"first_month_year":number|null,',
    '"lines":{"<key>":{"measure":"<measure or none>","unit":"<unit>"}}} — one entry per key given.',
  ].filter(Boolean).join('\n');

  // The FILE is part of the key: two years' dashboards share a template, and a
  // template's meaning may be reused but a document's year never is — reused,
  // last year's answer put this year's electricity a year early.
  const fingerprint = decisionFingerprint([
    'esgmonthly',
    context.filename,
    table.title.join('|'),
    table.corner,
    table.months.join(','),
    ...sample.map((s) => s.key).sort(),
  ]);

  try {
    const decision = await rememberDecision<TableReading | null>('esgmonthly', fingerprint, async () => {
      const ask = model.completeHard?.bind(model) ?? model.complete.bind(model);
      const reply = await ask(SYSTEM, user);
      const json = JSON.parse(reply.slice(reply.indexOf('{'), reply.lastIndexOf('}') + 1)) as Record<string, any>;
      const read: Record<string, LineReading> = {};
      for (const [key, value] of Object.entries((json.lines ?? {}) as Record<string, any>)) {
        const measure = String(value?.measure ?? 'none');
        read[key] = {
          measure: (measure in ESG_MONTHLY_MEASURES ? measure : 'none') as LineReading['measure'],
          unit: String(value?.unit ?? 'other'),
        };
      }
      const year = Number(json.first_month_year);
      return {
        linesAre: json.lines_are === 'measures' ? 'measures' : json.lines_are === 'other' ? 'other' : 'sites',
        site: typeof json.site === 'string' && json.site.trim() ? json.site.trim() : null,
        firstMonthYear: Number.isInteger(year) && year > 1990 && year < 2100 ? year : null,
        lines: read,
      };
    });
    const reading = decision.value;
    if (!reading) return null;
    // A file that states its year range ("DASHBOARD 2025-2026") bounds the
    // answer: the first month falls in one of those two years, whatever was said.
    const range = statedYearRange(context.filename, ...table.title, context.sheetName ?? '');
    if (range && !table.years[0] && reading.firstMonthYear !== range[0] && reading.firstMonthYear !== range[1]) {
      return { ...reading, firstMonthYear: table.months[0] >= 7 ? range[0] : range[1] };
    }
    return reading;
  } catch (err) {
    logger.warn('Monthly table could not be read', { file: context.filename, sheet: context.sheetName, reason: (err as Error).message });
    return null;
  }
}

/* ------------------------------------------------------------------ *
 * Facts
 * ------------------------------------------------------------------ */

function monthEnd(year: number, month: number): string {
  const last = new Date(Date.UTC(year, month, 0)).getUTCDate();
  return `${year}-${String(month).padStart(2, '0')}-${String(last).padStart(2, '0')}`;
}

/** Calendar year of every month in the run: stated, or counted on from the first. */
export function yearsOf(table: Pick<MonthTable, 'months' | 'years'>, firstMonthYear: number | null): Array<number | null> {
  const out: Array<number | null> = [];
  let year: number | null = table.years[0] ?? firstMonthYear;
  table.months.forEach((month, i) => {
    if (i > 0 && month < table.months[i - 1] && year !== null) year += 1;
    out.push(table.years[i] ?? year);
  });
  return out;
}

export function tableFacts(table: MonthTable, reading: TableReading): { facts: EsgMonthlyFact[]; notes: string[] } {
  const facts: EsgMonthlyFact[] = [];
  const notes: string[] = [];
  // Lines that are vehicles or people are not this reader's to read.
  if (reading.linesAre === 'other') return { facts, notes };
  const years = yearsOf(table, reading.firstMonthYear);
  if (years.some((y) => y === null)) {
    notes.push(`The year of the months in "${table.title.join(' / ') || 'a monthly table'}" could not be told, so its figures were not used.`);
    return { facts, notes };
  }

  for (const line of table.lines) {
    if (line.isTotal) continue;
    const read = reading.lines[lineKey(line)];
    if (!read || read.measure === 'none') continue;
    const stored = ESG_MONTHLY_MEASURES[read.measure].unit;
    const factor = UNIT_FACTORS[stored]?.[read.unit];
    if (factor === undefined) {
      notes.push(`"${line.label}" is stated in ${read.unit}, which cannot be converted to ${stored}; it was not used.`);
      continue;
    }
    const site = reading.linesAre === 'sites' ? (line.label || null) : reading.site;
    line.values.forEach((value, i) => {
      if (value === null) return;
      facts.push({
        measure: read.measure as EsgMonthlyMeasure,
        site,
        period_end: monthEnd(years[i] as number, table.months[i]),
        value: Math.round(value * factor * 1e6) / 1e6,
        unit: stored,
      });
    });
  }
  return { facts, notes };
}

export interface EsgMonthlySheetInput {
  filename: string;
  sheetName?: string;
  /** Raw cell values, row by row — the reader needs the layout, not header-keyed rows. */
  matrix?: unknown[][];
  hidden?: boolean;
}

/**
 * Read a sheet's site × month tables. Null when the sheet holds none (the
 * caller's other readers stand), or when none of its lines is a measure the
 * workbook keeps.
 */
export async function extractEsgMonthlyTables(
  model: ExtractionModel,
  input: EsgMonthlySheetInput,
): Promise<DocumentExtraction | null> {
  const matrix = input.matrix;
  if (!matrix || matrix.length === 0) return null;
  const tables = findMonthTables(matrix);
  if (tables.length === 0) return null;

  const facts: EsgMonthlyFact[] = [];
  const exceptions: string[] = [];
  let previous: { table: MonthTable; reading: TableReading } | null = null;
  for (const table of tables) {
    let reading: TableReading | null;
    if (table.continues && previous) {
      // The same table's second half: same meaning, and its months carry on
      // from where the first half stopped (Dec → Jan is the next year).
      const prior: { table: MonthTable; reading: TableReading } = previous;
      const priorYears = yearsOf(prior.table, prior.reading.firstMonthYear);
      const lastYear: number | null = priorYears[priorYears.length - 1];
      const lastMonth: number = prior.table.months[prior.table.months.length - 1];
      reading = {
        ...prior.reading,
        firstMonthYear: lastYear === null ? null : table.months[0] <= lastMonth ? lastYear + 1 : lastYear,
      };
    } else {
      reading = await readTable(model, table, input);
    }
    if (!reading) continue;
    previous = { table, reading };
    const read = tableFacts(table, reading);
    facts.push(...read.facts);
    exceptions.push(...read.notes);
  }
  if (facts.length === 0) return null;
  if (input.hidden) {
    exceptions.push(
      `These monthly figures were read from a HIDDEN sheet ("${input.sheetName}"). Hidden sheets are often left out of a company's own totals — confirm they belong in this report.`,
    );
  }

  logger.info('Read monthly tables deterministically', {
    file: input.filename,
    tables: tables.length,
    facts: facts.length,
    hidden: Boolean(input.hidden),
  });

  return {
    documentId: 'esg_monthly_tables',
    documentName: `${input.sheetName ?? input.filename} monthly figures`,
    sourceFile: input.filename,
    values: [{
      field: 'esg_monthly_rows',
      value: facts.map((fact) => ({
        monthly_measure: fact.measure,
        monthly_site: fact.site,
        monthly_period_end: fact.period_end,
        monthly_value: fact.value,
        monthly_unit: fact.unit,
      })),
      sourceFile: input.filename,
      sourceDocumentId: 'esg_monthly_tables',
    }],
    missingFields: [],
    unexpectedFields: [],
    exceptions,
  };
}
